/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Logica;

import static ConexSQL.Conexion.getConeccion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import poo.proveedor;

/**
 *
 * @author Montzerrat Rivera
 */
public class Ad_Inventario extends javax.swing.JFrame {

    proveedor prov;

    /**
     * Creates new form Inventario
     */
    public Ad_Inventario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxNombre = new javax.swing.JTextField();
        jtxTelefono = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Usuario.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/TELEFONO.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, -1, -1));

        jtxNombre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jtxNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 240, 40));

        jtxTelefono.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jtxTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 240, 40));

        btnAgregar.setBackground(new java.awt.Color(123, 175, 77));
        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 470, 100, 40));

        jButton1.setBackground(new java.awt.Color(123, 175, 77));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(867, 635, 100, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/PROVEEDOR.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        prov = new proveedor(jtxNombre.getText(), jtxTelefono.getText());        
        prov.setNombreProv(jtxNombre.getText());
        queryInsert(prov);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Ad_Productos acc = new Ad_Productos();
        acc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void queryInsert(proveedor prv) {
        Connection con = getConeccion();
        PreparedStatement pst;
        ResultSet rst;
        String scriptSQL = "INSERT INTO TBL_Proveedor (id_proveedor, "
                + "nom_prove, telefono) VALUES (" + prv.toQuerySQL() + ")";
        System.out.println(scriptSQL);
        
        try {
            con.setAutoCommit(false);
            pst = con.prepareStatement(scriptSQL);
            pst.executeUpdate();
            
            int value = JOptionPane.showConfirmDialog(this, "¿CONFIRMAS LOS DATOS? \n Proveedor: "
                    +prv.getNombreProv()+"\nTelefono: "+prv.getTelefono(), "ATENCIÓN", JOptionPane.WARNING_MESSAGE);
            System.out.println("Valor Joption"+value);
            if (value == 0) {
                    con.commit();
                    JOptionPane.showMessageDialog(this, "Se agrego el proveedor: " + prv.getNombreProv() + " correctamente.");                    
                } else if (value == 2) {
                    JOptionPane.showMessageDialog(this, "No se agrego el proveedor");
                    con.rollback();
                }
            
            
        } catch (SQLException e) {
            System.out.println("Error: " +e);            
        }
    }

   /* public int getIdProveedor() {
        int idProveedor = 0;
        Connection con = getConeccion();
        PreparedStatement prepared;
        ResultSet result;

        try {
            prepared = con.prepareStatement("SELECT max(id_proveedor) "
                    + "FROM TBL_Proveedor");
            result = prepared.executeQuery();

            if (result.next()) {
                idProveedor = result.getInt("id_proveedor") + 1;
                System.out.println("idProveedor: " + idProveedor);
            }
        } catch (SQLException e) {
            System.out.println("Error: " +e);
        }

        return idProveedor;
    }*/

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ad_Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ad_Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ad_Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ad_Inventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ad_Inventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jtxNombre;
    private javax.swing.JTextField jtxTelefono;
    // End of variables declaration//GEN-END:variables
}
