/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Logica;

import static ConexSQL.Conexion.getConeccion;
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import poo.Productos;

/**
 *
 * @author Montzerrat Rivera
 */
public class Ad_Productos extends javax.swing.JFrame {

    List cbxProv = new ArrayList();
    List cbxProduct = new ArrayList();
    Productos prodcts = new Productos();
    Connection con = getConeccion();
    PreparedStatement prst;
    ResultSet rslt;

    /**
     * Creates new form Ad_Productos
     */
    public Ad_Productos() {
        initComponents();
        addCbxProv();
    }

    public void addCbxProv() {
        try {

            cbxProveedor.addItem("ELIGE UNA OPCIÓN");

            prst = con.prepareStatement("SELECT nom_prove FROM TBL_Proveedor");
            rslt = prst.executeQuery();
            while (rslt.next()) {
                cbxProv.add(rslt.getString("nom_prove"));
                cbxProveedor.addItem(rslt.getString("nom_prove"));
            }

        } catch (SQLException e) {
            System.out.println("Error en addCbxProv: " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtxNuevoProducto = new javax.swing.JTextField();
        cbxProveedor = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jtxtCostoProd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbxProducto = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btnNuevoProveedor = new javax.swing.JButton();
        jtxCantBodega = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar.setBackground(new java.awt.Color(123, 175, 77));
        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 480, 120, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/PEXIST.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, -1, -1));
        getContentPane().add(jtxNuevoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, 210, 30));

        cbxProveedor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxProveedorItemStateChanged(evt);
            }
        });
        getContentPane().add(cbxProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 180, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/PRO.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, -1, -1));

        jtxtCostoProd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jtxtCostoProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, 210, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/COUNITARIO.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, -1, -1));

        cbxProducto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxProductoItemStateChanged(evt);
            }
        });
        getContentPane().add(cbxProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 250, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/PNUEVO.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, -1, -1));

        btnNuevoProveedor.setBackground(new java.awt.Color(123, 175, 77));
        btnNuevoProveedor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnNuevoProveedor.setText("NUEVO PROVEEDOR");
        btnNuevoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoProveedorActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 180, 40));

        jtxCantBodega.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jtxCantBodega, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 392, 210, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/CLLEGADA.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, -1, 40));

        btnRegresar.setBackground(new java.awt.Color(123, 175, 77));
        btnRegresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegresar.setText("REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 645, -1, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/PRODUCTO.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoProveedorActionPerformed
        Ad_Inventario acc = new Ad_Inventario();
        acc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNuevoProveedorActionPerformed

    private void cbxProveedorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxProveedorItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            int index = cbxProveedor.getSelectedIndex();

            try {
                cbxProduct.clear();
                cbxProducto.removeAllItems();
                cbxProducto.addItem("ELIGE UNA OPCIÓN");
                prst = con.prepareStatement("SELECT nombre_prod FROM TBL_Producto WHERE id_proveedor = ?");
                prst.setInt(1, index);
                rslt = prst.executeQuery();
                while (rslt.next()) {
                    cbxProduct.add(rslt.getString("nombre_prod"));
                    cbxProducto.addItem(rslt.getString("nombre_prod"));
                }

            } catch (SQLException e) {
                System.out.println("Error en cbxProveedorItemStateChanged: " + e);
            }

        }
    }//GEN-LAST:event_cbxProveedorItemStateChanged

    private void cbxProductoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxProductoItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (!(cbxProducto.getSelectedIndex() == 0)) {
                jtxNuevoProducto.setText("");
                jtxNuevoProducto.setEnabled(false);
            } else if (cbxProducto.getSelectedIndex() == 0) {
                jtxNuevoProducto.setEnabled(true);
                jtxNuevoProducto.requestFocus();
            }
        }
    }//GEN-LAST:event_cbxProductoItemStateChanged

    public void ScriptIntert(String query) {

        try {
            con.setAutoCommit(false);
            prst = con.prepareStatement(query);
            prst.executeUpdate();
            int value = JOptionPane.showConfirmDialog(this, "¿CONFIRMAS LOS DATOS? \n"
                    + "PRODUCTO: " + prodcts.getNombreProd()
                    + "\nPRECIO: $" + prodcts.getPrecio()
                    + "\nCANT. BODEGA: " + prodcts.getCantBodega(), "ATENCIÓN", JOptionPane.WARNING_MESSAGE);
            System.out.println("Valor JOption" + value);
            if (value == 0) {
                con.commit();
                JOptionPane.showMessageDialog(this, "Se agrego el producto: " + prodcts.getNombreProd() + " correctamente.");
                Clear();
            } else if (value == 2) {
                JOptionPane.showMessageDialog(this, "No se agrego el producto");
                con.rollback();
            }
        } catch (SQLException e) {
            System.out.println("Error en ScriptIntert: " + e);
        }
    }

    public void ScriptUpdate(String query) {
        try {
            con.setAutoCommit(false);
            prst = con.prepareStatement(query);
            prst.executeUpdate();
            int value = JOptionPane.showConfirmDialog(this, "¿CONFIRMAS LOS DATOS? \n"
                    + "PRODUCTO: " + prodcts.getNombreProd(), "ATENCIÓN", JOptionPane.WARNING_MESSAGE);
            System.out.println("Valor JOption" + value);
            if (value == 0) {
                con.commit();
                JOptionPane.showMessageDialog(this, "Se agrego el producto: " + prodcts.getNombreProd() + " correctamente.");
                Clear();
            } else if (value == 2) {
                JOptionPane.showMessageDialog(this, "No se agrego el producto");
                con.rollback();
            }

        } catch (SQLException e) {
            System.out.println("Error en ScriptUpdate: " +e);
        }

    }

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String script = "null";
        //Producto nuevo
        try {
            if (cbxProducto.getSelectedIndex() == 0) {
                prodcts.setNombreProd(jtxNuevoProducto.getText());
                prodcts.setIdProvedor(cbxProveedor.getSelectedIndex());
                prodcts.setPrecio(new Double(jtxtCostoProd.getText()));
                prodcts.setCantBodega(new Integer(jtxCantBodega.getText()));
                //Producto nuevo Insert
                script = "INSERT INTO TBL_Producto (id_producto, nombre_prod,"
                        + "precio, cant_bodega, id_proveedor) VALUES"
                        + "(" + prodcts.toQuerySQL() + ")";
                ScriptIntert(script);
                
            } else if (!(cbxProducto.getSelectedIndex() == 0)) {
                prodcts.setNombreProd((String) cbxProducto.getSelectedItem());
                prodcts.setIdProvedor(cbxProveedor.getSelectedIndex());
                prodcts.setPrecio(new Double(jtxtCostoProd.getText()));
                prodcts.setCantBodega(new Integer(jtxCantBodega.getText()));
                //Producto ya activo Update
                script = "UPDATE TBL_Producto SET " + prodcts.toUpdateSQL();
                ScriptUpdate(script);

            }

            System.out.println(prodcts.toQuerySQL());
            System.out.println(script);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingresa valores validos");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        Supervisor acc = new Supervisor();
        acc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    public void Clear() {
        jtxCantBodega.setText("");
        jtxNuevoProducto.setText("");
        jtxtCostoProd.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ad_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ad_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ad_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ad_Productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ad_Productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnNuevoProveedor;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cbxProducto;
    private javax.swing.JComboBox<String> cbxProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jtxCantBodega;
    private javax.swing.JTextField jtxNuevoProducto;
    private javax.swing.JTextField jtxtCostoProd;
    // End of variables declaration//GEN-END:variables
}
