/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Logica;

import static ConexSQL.Conexion.getConeccion;
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import poo.Usuario;

/**
 *
 * @author Montzerrat Rivera
 */
public class Ad_Registro extends javax.swing.JFrame {

    String contra;
    int idUsr = 0;
    Usuario usr;
    int idUsuario = getIDpass();

    static Connection con = getConeccion();
    static PreparedStatement ps;
    static ResultSet res;

    /**
     * Creates new form Ad_Registro
     */
    public Ad_Registro() {
        initComponents();
        jLID.setText("ID: " + idUsuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLID = new javax.swing.JLabel();
        jtxName = new javax.swing.JTextField();
        cbx_Rol = new javax.swing.JComboBox<>();
        jtxPassword = new javax.swing.JTextField();
        generarPass = new javax.swing.JButton();
        btnAgregarUser = new javax.swing.JButton();
        areaSet = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLID.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLID.setText("ID: 001");
        getContentPane().add(jLID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 180, 30));

        jtxName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jtxName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 302, 240, 40));

        cbx_Rol.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbx_Rol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ELIGE UN ROL", "ADMINISTRADOR", "CAJERO", "SUPERVISOR" }));
        cbx_Rol.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbx_RolItemStateChanged(evt);
            }
        });
        getContentPane().add(cbx_Rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 302, 200, 30));

        jtxPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(jtxPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 240, 40));

        generarPass.setBackground(new java.awt.Color(123, 175, 77));
        generarPass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        generarPass.setText("GENERAR CONTRASEÑA");
        generarPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarPassActionPerformed(evt);
            }
        });
        getContentPane().add(generarPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, 220, 40));

        btnAgregarUser.setBackground(new java.awt.Color(123, 175, 77));
        btnAgregarUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAgregarUser.setText("ACEPTAR");
        btnAgregarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarUserActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, 120, 30));

        areaSet.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        areaSet.setText("AREA:");
        getContentPane().add(areaSet, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 382, 200, 30));

        jButton1.setBackground(new java.awt.Color(123, 175, 77));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(887, 645, 90, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Usuario.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Contraseña.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/REGISTRO.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbx_RolItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbx_RolItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {

            int index = cbx_Rol.getSelectedIndex();

            switch (index) {
                case 0:
                    JOptionPane.showMessageDialog(this, "Ingresa un Rol");
                    break;
                case 1:
                    areaSet.setText("AREA: Cafeteria");
                    break;
                case 2:
                    areaSet.setText("AREA: Cafeteria");
                    break;
                case 3:
                    areaSet.setText("AREA: Cafeteria");
                    break;
                default:
                    throw new AssertionError();
            }

        }
    }//GEN-LAST:event_cbx_RolItemStateChanged

    public boolean DataValid() {
        return !(jtxName.getText().equals("") || cbx_Rol.getSelectedIndex() == 0);
    }

    public void Clear() {
        jtxName.setText("");
        jtxName.setText("");
        cbx_Rol.setSelectedIndex(0);
    }

    private void btnAgregarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarUserActionPerformed
        if (DataValid() || jtxPassword.getText().equals("")) {
            Connection Conect = getConeccion();
            PreparedStatement preparedStm;
            usr = new Usuario(idUsuario, jtxPassword.getText(), jtxName.getText(), 100 + cbx_Rol.getSelectedIndex(), 401);
            System.out.println("SQL: " + usr.toQuerySQL());
            String querySQLInsert = "INSERT INTO TBL_Usuario(id_usuario, nombre_usr, contrasenia, id_rol, id_area) VALUES (" + usr.toQuerySQL() + ")";
            System.out.println(querySQLInsert);
            try {
                Conect.setAutoCommit(false);
                preparedStm = Conect.prepareStatement(querySQLInsert);
                preparedStm.executeUpdate();

                int value = JOptionPane.showConfirmDialog(this, "¿CONFIRMAS LOS DATOS?", "ATENCIÓN", JOptionPane.WARNING_MESSAGE);
                if (value == 0) {
                    Conect.commit();
                    JOptionPane.showMessageDialog(this, "Se agrego el usuario: " + usr.getNombreUsuario() + " correctamente.");
                    Administrador ex = new Administrador();
                    ex.show();
                    this.dispose();
                } else if (value == 1) {
                    Conect.rollback();
                    JOptionPane.showMessageDialog(this, "No se agrego al usuario");
                }

            } catch (SQLException e) {
                System.out.println("Error: " + e);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Inserta datos antes de agregar");
        }
    }//GEN-LAST:event_btnAgregarUserActionPerformed

    private void generarPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarPassActionPerformed
        if (DataValid()) {
            contra = (idUsuario + "_" + jtxName.getText() + "@" + cbx_Rol.getSelectedIndex());
            jtxPassword.setText(contra);
        } else {
            JOptionPane.showMessageDialog(this, "Ingresa datos para generar la contraseña");
        }
    }//GEN-LAST:event_generarPassActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Administrador acc = new Administrador();
        acc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ad_Registro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ad_Registro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ad_Registro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ad_Registro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ad_Registro().setVisible(true);
            }
        });
    }

    public int getIDpass() {

        try {
            ps = con.prepareStatement("SELECT max(id_usuario) as UsuarioMaximo "
                    + "FROM TBL_Usuario");
            res = ps.executeQuery();

            if (res.next()) {
                idUsr = res.getInt("UsuarioMaximo");
                //usr.setContrasenia(""+idUsr);
            }

        } catch (SQLException e) {
            System.out.println("Error: 232" + e);
        }
        return idUsr + 1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel areaSet;
    private javax.swing.JButton btnAgregarUser;
    private javax.swing.JComboBox<String> cbx_Rol;
    private javax.swing.JButton generarPass;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jtxName;
    private javax.swing.JTextField jtxPassword;
    // End of variables declaration//GEN-END:variables
}
