/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Logica;

import static ConexSQL.Conexion.getConeccion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author anmijurane <miguel.andres_sic@tesco.edu.mx>
 */
public class SignIn extends javax.swing.JFrame {
    static String Rol;
    /**
     * Creates new form SignIn
     */
    public SignIn() {
        initComponents();
    }
    
    public SignIn(String Rol){
        initComponents();
        SignIn.Rol = Rol;
        Usuario.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Usuario = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        access = new javax.swing.JButton();
        jPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Usuario.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Usuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 380, 70));

        btnBack.setBackground(new java.awt.Color(123, 175, 77));
        btnBack.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        btnBack.setText("REGRESAR");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 650, 130, 40));

        access.setBackground(new java.awt.Color(123, 175, 77));
        access.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        access.setText("INICIAR SESION");
        access.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accessActionPerformed(evt);
            }
        });
        getContentPane().add(access, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 590, 170, 70));

        jPassword.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 380, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/LOGIN.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accessActionPerformed
        
        try {
            Connection con = null;
            con = getConeccion();

            PreparedStatement ps;
            ResultSet res;

            ps = con.prepareStatement("SELECT nombre_usr FROM TBL_Usuario WHERE nombre_usr = ? and contrasenia = ? and id_rol = ?");
            ps.setString(1, Usuario.getText());
            ps.setString(2, new String(jPassword.getPassword()));
            ps.setString(3, Rol);

            res = ps.executeQuery();
            
            if (res.next()) {
                JOptionPane.showMessageDialog(null, "Bienvenido: " +res.getString("nombre_usr"));
                if (null != Rol) switch (Rol) {                
                    case "101": //Admon
                        Administrador admon = new Administrador(res.getString("nombre_usr"));
                        admon.setVisible(true);
                        this.dispose();
                        break;                
                    case "102": //Cajero
                        Cajero caj = new Cajero(res.getString("nombre_usr"));
                        caj.setVisible(true);
                        this.dispose();
                        break;
                    case "103": //Supervisor
                        Supervisor superv = new Supervisor(res.getString("nombre_usr"));
                        superv.setVisible(true);
                        this.dispose();
                        break;
                    default:
                        break;
                }
            }else{
                JOptionPane.showMessageDialog(null, "CREDENCIALES INCORRECTAS");
                Usuario.setText("");
                jPassword.setText("");
                Usuario.requestFocus();
            }
            
        } catch (Exception e) {
            System.out.println("Error: " +e);
        }
        
    }//GEN-LAST:event_accessActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Rol back = new Rol();
        back.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Usuario;
    private javax.swing.JButton access;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPassword;
    // End of variables declaration//GEN-END:variables
}
